### ISSUE TITLE
Homedisco doesn't work with Disco 0.2?

### ISSUE THREAD

**Issue by tuulos** [discoproject/disco#10]
22:54 < neal_> hi
22:55 < neal_> when i try to run homedisco i get the following error
22:55 < neal_> Traceback (most recent call last):
22:55 < neal_>   File "wordcount.py", line 1, in <module>
22:55 < neal_>     from homedisco import HomeDisco
22:55 < neal_>   File "/home/neal/school/seng474/frequent_itemsets/cfim/homedisco.py", line 4, in 
               <module>
22:55 < neal_>     from disconode import disco_worker
22:55 < neal_>   File "/usr/local/lib/python2.6/dist-packages/disconode/disco_worker.py", line 504, in 
               <module>
22:55 < neal_>     init()
22:55 < neal_>   File "/usr/local/lib/python2.6/dist-packages/disconode/disco_worker.py", line 64, in 
               init
22:55 < neal_>     OOB_URL = ("http://%s/disco/ctrl/oob_get?" % this_master())\
22:55 < neal_>   File "/usr/local/lib/python2.6/dist-packages/disconode/disco_worker.py", line 46, in 
               this_master
22:55 < neal_>     return sys.argv[4].split("/")[2]

**Comment by tuulos** [comment]
Fixed by caf78f7735673140d15cdc9e9aa1d990248a99b2
