### ISSUE TITLE
CommError: Unable to access resource...:Invalid HTTP reply (expected 200 got 404)

### ISSUE THREAD

**Issue by davin** [discoproject/disco#104]
On my dual core lap-cluster, I frequently get this error while looping through a sequence of chained map-reduce jobs.

CommError: Unable to access resource (http://localhost:8989/localhost/1a/myJob@4f3:2d8c:23d57/reduce-index.txt): Invalid HTTP reply (expected 200 got 404)

I suspect this is a matter of resource over-utilization on my underpowered laptop.  I'm wondering if there a timeout I could extend to avoid the error?

**Comment by davin** [comment]
FYI, the partial stack trace is:

Traceback (most recent call last):
  File "/home/disco/disco/pydisco/disco/core.py", line 435, in result_iterator
    res = [url for r in results for url in util.urllist(r)]
  File "/home/disco/disco/pydisco/disco/util.py", line 65, in urllist
    return parse_dir(url, partid=partid)
  File "/home/disco/disco/pydisco/disco/util.py", line 113, in parse_dir
    return parse_index(download(url).splitlines())
  File "/home/disco/disco/pydisco/disco/comm_curl.py", line 53, in download
    check_code(dl_handle, 200, url)
  File "/home/disco/disco/pydisco/disco/comm_curl.py", line 16, in check_code
    (expected, code), url)
CommError: Unable to access resource (http://localhost:8989/localhost/1a/myJob@4f3:2d8c:23d57/reduce-index.txt): Invalid HTTP reply (expected 200 got 404)
