### ISSUE TITLE
purge fails with ImportError

### ISSUE THREAD

**Issue by jseppanen** [discoproject/disco#143]
I have a result class that calls Disco(...).purge(jobname) in its **del** method. It worked fine in disco 0.2.6 but now I get this:

Traceback (most recent call last):
  File "/home/jarnsepp/foo/discotool.py", line 224, in **del**
    self.disco.purge(self.job.name)
  File "/home/jarnsepp/disco2/pydisco/disco/core.py", line 195, in purge
    self.request('/disco/ctrl/purge_job', '"%s"' % name)
  File "/home/jarnsepp/disco2/pydisco/disco/core.py", line 69, in request
    offset=offset)
  File "/home/jarnsepp/disco2/pydisco/disco/comm.py", line 39, in download
    from disco.util import urlresolve
ImportError: No module named disco.util

**Comment by jflatow** [comment]
Was this an issue with Disco or installation?
