### ISSUE TITLE
DISCO_EVENTS=1 makes the client die but lets the job live.

### ISSUE THREAD

**Issue by tmielika** [discoproject/disco#182]
When running a disco job with DISCO_EVENT=1, the client seems to consistently lose the connection to the master right after seeing the first event, while the job itself continues running.
---clip---
Traceback (most recent call last):
  File "temp_scripts/maps_route_clicks.py", line 100, in <module>
    for k,v in result_iterator(job.wait()):
  File "/home/tmielika/src/disco/lib/disco/core.py", line 360, in wait
    event_monitor.refresh()
  File "/home/tmielika/src/disco/lib/disco/eventmonitor.py", line 164, in refresh
    status = self.status
  File "/home/tmielika/src/disco/lib/disco/eventmonitor.py", line 155, in status
    return "Status: [%s] %d waiting, %d running, %d done, %d failed" % tuple(self.stats)
  File "/home/tmielika/src/disco/lib/disco/eventmonitor.py", line 148, in stats
    jobinfo = self.job.jobinfo()
  File "/home/tmielika/src/disco/lib/disco/core.py", line 313, in jobinfo
    return json.loads(self.request('/disco/ctrl/jobinfo?name=%s' % name))
  File "/home/tmielika/src/disco/lib/disco/core.py", line 69, in request
    offset=offset)
  File "/home/tmielika/src/disco/lib/disco/comm.py", line 88, in download
    headers=range_header(offset)).read()
  File "/home/tmielika/src/disco/lib/disco/comm.py", line 81, in request
    raise CommError(response.read(), url, response.status)
disco.error.CommError: Unable to access resource (disco://disco2/disco/ctrl/jobinfo?name=ovi:map:superclicks@500:c132a:ae627): Internal server error (is disco master running at disco://disco2?) (HTTP status 500)
---clap---

**Comment by tuulos** [comment]
related to #183

**Comment by jflatow** [comment]
Server should actually return 503 in cases where it is busy instead of 500, then the client can retry without wrapping each case specially. Also applies for issue #183.

**Comment by jflatow** [comment]
client now retries for all unexpected connection errors, which prevents this issue. however, if there actually is a real reason why it cant make a request, it takes a while for the user to find out (due to longish backoff periods)
