### ISSUE TITLE
test_save sometimes fails.

### ISSUE THREAD

**Issue by pooya** [discoproject/disco#405]
The error messages are something like this:

Traceback (most recent call last):
  File "/home/shayan/disco/tests/test_save.py", line 64, in test_save
    self.assertAllEqual(sorted(self.results(b)),
  File "/usr/lib/python2.6/site-packages/disco/core.py", line 413, in classic_iterator
    for record in Input(dest, open=worker.opener('map', 'in', params)):
  File "/usr/lib/python2.6/site-packages/disco/worker/**init**.py", line 545, in **iter**
    iter = self.input_iter(self.input)
  File "/usr/lib/python2.6/site-packages/disco/worker/**init**.py", line 555, in input_iter
    return InputIter(self.input, task=self.task, **self.kwds)
  File "/usr/lib/python2.6/site-packages/disco/worker/**init**.py", line 497, in **init**
    self.swap()
  File "/usr/lib/python2.6/site-packages/disco/worker/**init**.py", line 520, in swap
    self.swap(traceback.format_exc())
  File "/usr/lib/python2.6/site-packages/disco/worker/**init**.py", line 520, in swap
    self.swap(traceback.format_exc())
  File "/usr/lib/python2.6/site-packages/disco/worker/**init**.py", line 524, in swap
    "last error was:\n\n{0}".format(error), self.input)
DataError: Unable to access resource ([u'disco://node02/ddfs/vol0/blob/9c/SaveJob2@56e:3e9d7:918d0:2:2:reduce:0--2-ec-23809$56e-3ea6f-3686a#0', u'disco://dev-node01/ddfs/vol0/blob/9c/SaveJob2@56e:3e9d7:918d0:2:2:reduce:0--2-ec-23809$56e-3ea6f-3686a#0']): Exhausted all available replicas, last error was:

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/disco/worker/**init**.py", line 518, in swap
    self.iter = skip(self.open(next(self.urls)), self.last + 1)
  File "/usr/lib/python2.6/site-packages/disco/worker/classic/worker.py", line 442, in open
    return ClassicFile(url, streams, params)
  File "/usr/lib/python2.6/site-packages/disco/worker/task_io.py", line 345, in **init**
    fd = stream(fd, size, url, _maybe_params)
  File "/usr/lib/python2.6/site-packages/disco/worker/task_io.py", line 36, in task_input_stream
    return schemes.input_stream(stream, size, url, params, globals=globals())
  File "/usr/lib/python2.6/site-packages/disco/schemes/**init**.py", line 35, in input_stream
    return input_stream(stream, size, url, params)
  File "/usr/lib/python2.6/site-packages/disco/schemes/scheme_disco.py", line 19, in input_stream
    file = open(url, task=globals().get('Task'))
  File "/usr/lib/python2.6/site-packages/disco/schemes/scheme_disco.py", line 13, in open
    return comm.open_url(util.urljoin((scheme, netloc, path)))
  File "/usr/lib/python2.6/site-packages/disco/comm.py", line 104, in open_url
    return open_remote(url, *args, *_kwargs)
  File "/usr/lib/python2.6/site-packages/disco/comm.py", line 110, in open_remote
    return Connection(urlresolve(url), token)
  File "/usr/lib/python2.6/site-packages/disco/comm.py", line 146, in **init**
    self.read(1)
  File "/usr/lib/python2.6/site-packages/disco/comm.py", line 172, in read
    bytes = self._read_chunk(size if size > 0 else CHUNK_SIZE)
  File "/usr/lib/python2.6/site-packages/disco/comm.py", line 192, in _read_chunk
    headers=headers)
  File "/usr/lib/python2.6/site-packages/disco/comm.py", line 80, in request
    raise CommError(response.read(), url, status)
CommError: Unable to access resource (http://dev-node01:8989/ddfs/vol0/blob/9c/SaveJob2@56e:3e9d7:918d0:2:2:reduce:0--2-ec-23809$56e-3ea6f-3686a#0): Not found. (404)

**Comment by pooya** [comment]
Closing because this test has been running reliably for a long time now.
